services:
  dbService:
    image: docker.io/library/postgres:17
    container_name: classytime_db_service
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5440:5432"
    volumes:
      - classytime_db_data:/var/lib/postgresql/data
    networks:
      - classytime_network

networks:
  classytime_network:
    driver: bridge

volumes:
  classytime_db_data:
